esphome:
  name: modbus-server-test

esp32:
  board: esp-wrover-kit
  variant: esp32
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password
  encryption:
    key: "y8Qw1nZr2Jv5LkT9sXc4Pq6HbGfEoUaVwM3iJtYpRNs="

ota:
  - platform: esphome
    password: "selrac"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test Cli Fallback Hotspot"
    password: "2SQAyLXpJcH3"

captive_portal:

binary_sensor:
  - platform: gpio
    pin:
      number: 16
      mode:
        input: true
        pullup: true
    name: "Switch Test"
  - platform: modbus_controller
    id: modbus_switch_test
    modbus_controller_id: modbus_controller_1
    register_type: coil
    address: 15

uart:
  - id: uart_modbus_server_1
    tx_pin: 23
    rx_pin: 22
    baud_rate: 115200

modbus:
  - id: modbus1
    uart_id: uart_modbus_server_1
    flow_control_pin: 18
    role: server

modbus_controller:
  - id: modbus_controller_1
    modbus_id: modbus1
    address: 20
    server_registers:
      - address: 0x0001
        value_type: U_WORD
        read_lambda: |-
          return 0x8;
      - address: 0x0002
        value_type: U_WORD
        read_lambda: |-
          return (random_uint32() % 100);

